apiVersion: v1
kind: Service
metadata:
  name: mainloop-frontend
  namespace: mainloop
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: mainloop-backend
  namespace: mainloop
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30800
