apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mainloop-manage-shim-secrets
  namespace: mainloop-shim-secrets
rules:
  - apiGroups: ['']
    resources: [secrets]
    verbs: [create, get, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mainloop-manage-shim-secrets
  namespace: mainloop-shim-secrets
subjects:
  - kind: ServiceAccount
    name: mainloop-backend
    namespace: mainloop-control
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mainloop-manage-shim-secrets
