apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mainloop

resources:
  - ../../base
  - httproute.yaml # Tailscale Gateway routes (prod-only)
  - database.yaml # CloudNativePG (prod-only)
  - 1password.yaml # 1Password Connect integration

patches:
  # Patch CloudNativePG storage class
  - path: database-patch.yaml
    target:
      kind: Cluster
      name: mainloop-db
  - path: shutdown-patch.yaml
